### ISSUE TITLE
Add component 'date input'

### ISSUE THREAD

**Issue by JamesDPC** [nswdpc/waratah#87]
Added in 3.14.2

We can implement this via a template for datetime-inputs module.

**Comment by JamesDPC** [comment]
DateCompositeField, with no placeholders

![image](https://github.com/nswdpc/waratah/assets/69664712/d1ee3c0e-8713-417c-be1c-a7df0d523662)


DatetimeCompositeField, with placeholder values

![image](https://github.com/nswdpc/waratah/assets/69664712/35c99e5a-f4e0-4383-aeb2-485a22b44684)

**Comment by JamesDPC** [comment]
If we want the placeholder attributes, which provide hinting, to be completely readable on wider forms, the style needs to be overridden here so that the fields take up the full width of the continer.

Looks like setting  `.nsw-form__date-input` / `--large` width as auto would do that.

Would also maintain consistency with other fields in a form.

**Comment by JamesDPC** [comment]
Full width example, with field above for comparison



![image](https://github.com/nswdpc/waratah/assets/69664712/65f1e56a-2f13-426e-826f-30d282508f63)

Sidebar example, with picker field for comparison. In narrow contexts, the picker field would be better and also native on mobile

![image](https://github.com/nswdpc/waratah/assets/69664712/a76229e7-5950-4ed8-a1ee-46a73eac9ff2)



@tardinha full width or no ?

**Comment by tardinha** [comment]
It looks nice, except for the placeholder text in the narrow width.

**Comment by JamesDPC** [comment]
> It looks nice, except for the placeholder text in the narrow width.

In the sidebar context, I'd lean to using a standard date input field or clear the default placeholders in the fields. Just an attribute on the field.

**Comment by JamesDPC** [comment]
resolved in #93
