### ISSUE TITLE
Allow line break in long agency names

### ISSUE THREAD

**Issue by tardinha** [nswdpc/waratah#9]
Agencies with long names need a ```<br>``` added to force a second line.

[See third example](https://digitalnsw.github.io/nsw-design-system/components/header/blank.html).

**Comment by JamesDPC** [comment]
Hmm, I think best option here is setting a width on `.nsw-header__title` to force wrap. The field for this text is text-only.

Maybe it could be a TextareaField and then nl2br() the value.

**Comment by tardinha** [comment]
yeah... DCS said to use a HTML field :P

Being able to choose where the line break goes is the important part, so nl2br() works perfectly!

**Comment by JamesDPC** [comment]
Try: https://github.com/nswdpc/waratah/tree/feat-longtitle

https://github.com/nswdpc/waratah/compare/feat-longtitle..master

**Comment by tardinha** [comment]
Tested and confirmed!

**Comment by JamesDPC** [comment]
Resolved with #20
